language: node_js
node_js:
  - 7

cache:
  directories:
    - node_modules

deploy:
  github_token: $GITHUB_TOKEN
  local_dir: src
  provider: pages
  skip_cleanup: true
  target_branch: master
  on:
    branch: development
